version: "3.8"
services:
  frontendvisualizer:
    container_name: frontendvisualizer
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-frontendapp  
    ports:
      - "3000:80"
    networks:
      - blitzvideo-api_default

networks:
  blitzvideo-api_default:
    external: true

