version: "3.8"
services:
  frontendvisualizer:
    container_name: frontendvisualizer
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-frontendapp  
      args:
        CLIENT_ID: "1"      
        CLIENT_SECRET: "QpDBKw1dSybJhsrbx4l2dmAVp05FFY15Alv0ETjH"
    ports:
      - "3000:80"
    networks:
      - blitzvideo-api_default

networks:
  blitzvideo-api_default:
    external: true

